### ISSUE TITLE
Modx resources browser opens blank window (Nightly 2.3.0 Nov 22)

### ISSUE THREAD

**Issue by wandering213** [modxcms/TinyMCE#3]
When opening the resources browser from the insert/edit image dialog I get a new window but its blank with no error message. I can reproduce the problem in Chrome (32.0.1700.55), Firefox 25.0.1, and IE 11.

**Comment by pyrographics** [comment]
This appears to still be an issue with the latest MODX 2.3 July 2 dev build.

**Comment by pyrographics** [comment]
This issue appears to be resolved in MODX 2.3.1.

**Comment by rthrash** [comment]
thanks for confirming
